name: Build README

on:
  schedule:
    - cron: '50 22 * * *' # at 22:55
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # Install node
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true

    - name: Update README
      run: |-
        node main.js
        awk '{$1=$1+1}1' readme.md > tmp
        mv tmp readme.md
        cat readme.md

    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "dominykas.guzys@gmail.com"
        git config --global user.name "Pufikas"
        git add -A
        git commit -m "Updated readme" || exit 0
        git push
