name: testing
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  schedule:
    - cron: '* * * * *' # 5mins

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Check the repo
      uses: actions/checkout@v2
    - name: Configure Git
      run: |-
        git config --global user.email "dominykas.guzys@gmail.com"
        git config --global user.name "Pufikas"
    - name: Generate the profile
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        WAKATIME_TOKEN: ${{ secrets.WAKATIME_TOKEN }}
      run: |-
        git diff
        git pull
        git add -A
        git commit -m "Daily: update" || exit 0
        git push
